### ISSUE TITLE
Consider later on whether to open source the project

### ISSUE THREAD

**Issue by gavargas22** [Matthew-Hiebing/Python-Math-Game#5]
It might be a good idea for you to put on your software portfolio that you have contributed/created open source software.

The potential employer can go to your github, download it and check it out. This has given me an edge for sure on interviews.

**Comment by Matthew-Hiebing** [comment]
Is the project considered open source now that its public?

**Comment by gavargas22** [comment]
yes,  you have to add an open source license like MIT or so

**Comment by Matthew-Hiebing** [comment]
I added an MIT license to both projects.
